### ISSUE TITLE
Japanese Trailer 1

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/LoD-Translation#7]
https://youtu.be/Hb5-8NDU7UE

**Comment by Manslapper** [comment]
(0:05 : Text) Everything began with a single divine tree.
(0:20 : Text) [Left: 108] [Bottom Right: Truth] [Upper Left: Winglies] [Right: Evil Eye] [Upper Right: Moon That Never Sets] [Lower Left: Black Monster] [Center: Myth] [Lower Right: Virage]
(0:24 : Voice) So, this is her.
(0:26 : Voice) Kanzas!
(0:28 : Voice) But I'm taking you with me!
(0:30 : Voice) That is not your concern.
(0:33 : Voice) Belzac...
(0:36 : Voice) ZIIIIEEEEEEG!!
(0:40 : Voice) I won't let you die in vain.
(0:43 : Text) Seven dragoons etched in legend
(1:14 : Text) Guided by fate, and
(1:16 : Text) Defying it.
(1:42 : Text) Now, more than 10,000 years have passed...
